---
- hosts: tag_ansible_managed
  tasks:
  - name: install additional packages
    package:
      name: ['vim','python2-pip','tmux','htop','jq']
    become: true
  - name: "install python libraries for aws"
    pip:
      name: ['boto', 'awscli']
    become: true
    when: environment_enable_aws == true
  - name: install bashrc
    template:
      src: templates/bashrc_managed.j2
      dest: "{{ ansible_user_dir }}/.bashrc"

